-- Existing pilot schema, versioned for reproducible setup. No invoice storage.
-- Apply deliberately in the dedicated Supabase SQL editor; never at startup.
begin;
create table if not exists public.settlemesh_registry (id integer primary key, schema_name text not null, document jsonb not null, updated_at timestamptz not null default now());
create table if not exists public.settlemesh_members (
  id uuid primary key default gen_random_uuid(), organization_id text not null, email text not null unique,
  password_hash text not null, role text not null check (role in ('owner','admin','viewer')), created_at timestamptz not null default now()
);
alter table public.settlemesh_members add column if not exists mfa_secret text, add column if not exists mfa_enabled boolean not null default false;
create table if not exists public.settlemesh_sessions (
  id uuid primary key, member_id uuid not null references public.settlemesh_members(id) on delete cascade,
  organization_id text not null, role text not null, expires_at timestamptz not null, created_at timestamptz not null default now()
);
create table if not exists public.settlemesh_requirements (
  id uuid primary key default gen_random_uuid(), organization_id text not null unique,
  company_name text not null, legal_name text not null, country text not null default '', vat_id text not null default '', peppol_id text not null default '',
  accepted_formats jsonb not null default '[]', accepted_currencies jsonb not null default '[]', requirements jsonb not null default '{}',
  version integer not null default 1, published boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.settlemesh_metrics (
  id bigint generated by default as identity primary key, organization_id text not null, day text not null,
  action text not null check (action in ('checklink_copied','invoice_checked','invoice_ready')), count integer not null default 1, created_at timestamptz not null default now()
);
alter table public.settlemesh_registry enable row level security;
alter table public.settlemesh_members enable row level security;
alter table public.settlemesh_sessions enable row level security;
alter table public.settlemesh_requirements enable row level security;
alter table public.settlemesh_metrics enable row level security;
-- No public SQL policies: browsers use only the authorized server routes.
revoke all on public.settlemesh_registry, public.settlemesh_members, public.settlemesh_sessions, public.settlemesh_requirements, public.settlemesh_metrics from anon, authenticated;
create index if not exists settlemesh_metrics_org_day_id on public.settlemesh_metrics(organization_id,day,id);
create index if not exists settlemesh_sessions_member on public.settlemesh_sessions(member_id);
-- Concurrent upserts receive atomic versions once this migration is applied.
create or replace function public.settlemesh_requirements_version() returns trigger
language plpgsql set search_path = public as $$
begin
  new.version := old.version + 1;
  new.updated_at := now();
  return new;
end;
$$;
create or replace trigger settlemesh_requirements_version before update on public.settlemesh_requirements
  for each row execute function public.settlemesh_requirements_version();
commit;
